# .streamlit/config.toml
# Created by Jonathan Astacio and Vek Unbound
# Copyright © 2025. All Rights Reserved.

[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showErrorDetails = true

[general]
# Set your startup script here
mainScript = "startup.py"
