[server]
headless = true

[theme]
base = "dark"

[general]
browserServerAddress = "localhost"
browserGatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
showSidebarNavigation = false

[server]
port = 8501

[global]
developmentMode = false

[streamlit]
script = "startup.py"
