[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"

[general]
email = "your-email@example.com"

[runner]
magicEnabled = true

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false

[app]
script = "app.py"
