# .streamlit/config.toml
# Created by Jonathan Astacio and Vek Unbound
# Copyright © 2025. All Rights Reserved.

[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#08FDD8"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#F8F8F2"
font = "sans serif"
