[server]
headless = true

[theme]
primaryColor = "#F63366"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[general]
# Set your main entry point
mainScript = "startup.py"
