[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"

[client]
showErrorDetails = true

[global]
developmentMode = false

[runner]
magicEnabled = false

[server.fileWatcherType]
value = "poll"

[settings]
mainScript = "startup.py"
