[general]
mainScript = "app.py"

[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#000000"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
