[server]
headless = true
port = 8501

[theme]
base = "dark"

[client]
showSidebarNavigation = false

[runner]
magicEnabled = true
fastReruns = true

[global]
developmentMode = false

[streamlit]
script = "startup.py"
